// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nlnvvjjegwbimfagqitq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5sbnZ2amplZ3diaW1mYWdxaXRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyOTk5NTksImV4cCI6MjA2MTg3NTk1OX0.KuMEZ89AbB751EJsyvD_HY5fMkvEb2S5ZyszsTNUnlI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);